# Generated by Django 4.1.7 on 2023-05-12 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cinema_name', models.CharField(max_length=100)),
                ('location_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year_of_release', models.DateField()),
                ('country', models.CharField(max_length=120)),
                ('directors', models.CharField(max_length=100)),
                ('stars', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('hall_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('birthday_date', models.DateTimeField()),
                ('photo_profile', models.ImageField(upload_to='images/')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('card_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time', models.DateTimeField()),
                ('seat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('row', models.IntegerField()),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=12)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.ticket')),
            ],
        ),
    ]
