# Generated by Django 4.1.7 on 2023-05-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='cast',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='venue',
            new_name='country_of_production',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='date',
            new_name='premiere_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='start',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='distributor',
            field=models.CharField(default='Almaty', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Almaty', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='year_of_release',
            field=models.IntegerField(default=1),
        ),
    ]
