# Generated by Django 4.1.7 on 2023-05-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
    ]
