# Generated by Django 4.1.7 on 2023-05-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_description_movie_cast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='des'),
            preserve_default=False,
        ),
    ]
