# Generated by Django 4.1.7 on 2023-05-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_movie_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='distributor',
        ),
    ]
