# Generated by Django 4.2.1 on 2023-05-14 20:43

import booking.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Almaty', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 18), validators=[booking.models.validate_date]),
        ),
    ]
