# Generated by Django 4.2.1 on 2023-05-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_event_price_event_city_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='Almaty', max_length=120),
        ),
    ]
