# Generated by Django 4.2.1 on 2023-05-14 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_event_city_place_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='quantity',
        ),
    ]
