# Generated by Django 4.1.7 on 2023-05-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_ticket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_type',
            field=models.CharField(default='vip', max_length=100),
            preserve_default=False,
        ),
    ]
